@BASE_URL_GATEWAY_SERVICE = https://microservices-private.sit.bravo.bfi.co.id/lora-gateway
@BASE_URL_GATEWAY_SERVICE = http://localhost:8081
@BASE_URL_LTS = https://microservices-private.sit.bravo.bfi.co.id/lora-task
@BASE_URL_LTS = http://localhost:8082
@LICENSE_PLATE = B2234CZ
@UUID = f33a20c9-0004-4d21-9df0-c45199671922


###

# @name start_application 
POST {{BASE_URL_GATEWAY_SERVICE}}/application/start HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "id": "{{UUID}}",
  "name": "dp-ndf-v0_0_1"
}

###

# @name set_to_start_bpkb_review_after_ekyc
POST {{BASE_URL_GATEWAY_SERVICE}}/application/{{UUID}}/data HTTP/1.1
Content-Type: application/json

{
  "$.asset.license_plate": "F0194QF",
  "$.customer.domicile.address.street_address": "Jl. villa permata",
  "$.status.application": "pre_approved",
  "$.customer.ktp.name": "Wadina Demi",
  "$.asset.bpkb_address": "Jl. villa permata",
  "$.survey_appointment.preferred_timezone": "Asia/Jakarta",
  "$.survey_appointment.survey_type": "INSTANT",
  "$.loan_structure.product_id": 2,
  "$.process.survey_task.survey_branch_id": "402",
  "$.process.survey_task.surveyor_employee_id": "000000",
  "$.process.operations_task.processing_branch_id": "402",
  "$.submission_date": "2025-04-08T15:30:00Z",
  "$.asset.bpkb_number": "D123456789",
  "$.asset.bpkb_owner_name": "BUDI",
  "$.asset.asset_code": "MTRHONDA.VARIO.125FICBS",
  "$.asset.manufacturing_year": "2024",
  "$.asset.unit_color": "BLUE",
  "$.asset.chassis_number": "P1234567890129831",
  "$.asset.engine_number": "E1234567890",
  "$.asset.bpkb_invoice_number": "INV/2025/03/12/01ABC",
  "$.channel.ekyc_authority": "partner",
  "$.documents.bpkb_page_1.document_id": "845db5fb-cd70-4e37-a220-ad4b66bb4c85",
  "$.documents.bpkb_page_2.document_id": "f64d342b-581a-4a71-bee9-8ee9cd582d44",
  "$.documents.bpkb_page_3.document_id": "03f3dfcf-54ce-488d-9bcf-328a11e20be5",
  "$.documents.bpkb_page_4.document_id": "03f3dfcf-54ce-488d-9bcf-328a11e20be5",
  "$.documents.bpkb_page_5.document_id": "03f3dfcf-54ce-488d-9bcf-328a11e20be5",
  "$.documents.bpkb_invoice.document_id": "760fc814-433e-4b80-8a02-b84595148309",
  "$.documents.bpkb_receipt_2.document_id": "03f3dfcf-54ce-488d-9bcf-328a11e20be5",
  "$.documents.debtor_signature.document_id": "845db5fb-cd70-4e37-a220-ad4b66bb4c85",
  "$.documents.spouse_signature.document_id": "f64d342b-581a-4a71-bee9-8ee9cd582d44",
  "$.documents.stnk.document_id": "1bc60281-3655-41c3-a4df-75ce2bbd57a8",
  "$.documents.tax_notice.document_id": "1bc60281-3655-41c3-a4df-75ce2bbd57a8",
  "$.documents.ktp.document_id": "1bc60281-3655-41c3-a4df-75ce2bbd57a8",
  "$.documents.spouse_ktp.document_id": "1bc60281-3655-41c3-a4df-75ce2bbd57a8",
  "$.asset.tax_expiration_date": "2025-03-12",
  "$.asset.stnk_number": "07654321",
  "$.asset.stnk_expiration_date": "2025-03-12",
  "$.asset.bpkb_ownership": "1",
  "$.documents.asset_document_status": "IN_TRANSIT_CUSTOMER_TO_BRANCH",
  "$.process.asset_pricing.price": 2500000,
  "$.loan_structure.admin_fee": 2500,
  "$.loan_structure.provision_fee": 500000,
  "$.loan_structure.max_funding": 30000000,
  "$.loan_structure.interest_rate": 0.5,
  "$.loan_structure.life_insurance_premium": 50000000,
  "$.loan_structure.product_offering": 35,
  "$.customer.ktp.birth_date": "1999-02-21",
  "$.customer.domicile.address.sub_district_code": "36.74.01.1005",
  "$.process.returning.customer_type": "NEW",
  "$.customer.personal.marital_status_code": "M",
  "$.customer.bank_information.account_name": "Data Test Yulia",
  "$.customer.bank_information.account_number": "111643252",
  "$.customer.bank_information.bank_id": "47",
  "$.loan_structure.tenure": 24,
  "$.loan_structure.amount": 10000000,
  "$.loan_structure.billing_date": "2025-05-30",
  "$.loan_structure.capitalized_ntf_amount": 1000000,
  "$.loan_structure.ltv": 0.87,
  "$.loan_structure.monthly_installment": 300000,
  "$.loan_structure.funding_ratio": 0.87,
  "$.process.operations_task.processing_branch_name": "Jambi",
  "$.process.survey_task.survey_branch_name": "Jambi",
  "$.customer.ktp.birth_place": "Bandung",
  "$.customer.ktp.gender": "M",
  "$.process.survey_task.bpkb_submission.submission_method": "BRANCH_DROPOFF",
  "$.survey_appointment.start_time": "2025-07-16T15:30:00Z",
  "$.survey_appointment.end_time": "2025-07-16T15:45:00Z",
  "$.survey_appointment.survey_location_type": "virtual",
  "$.survey_appointment.survey_resource_type": "vd",
  "$.channel.marketing_id": "2311NC0006",
  "$.customer.contact.mobile_number": "+628131131113",
  "$.status.reservation_expiry": "2024-03-12T14:30:00Z",
  "$.channel.marketing_id": "2311NC0006",
  "$.process.survey_task.bpkb_submission.submission_appointment_time": "2025-07-12T11:55:02Z",
  "$.customer.contact.mobile_number": "+628131131113",
  "$.survey_appointment.survey_resource_type": "vd",
  "$.survey_appointment.survey_type": "INSTANT",
  "$.survey_appointment.preferred_timezone": "Asia/Jakarta"
}
