@BASE_URL_GATEWAY_SERVICE = http://localhost:8081
@BASE_URL_LTS = http://localhost:8082
# @BASE_URL_LTS = https://microservices.sit.bravo.bfi.co.id/lora-task
# @BASE_URL_GATEWAY_SERVICE = https://microservices.sit.bravo.bfi.co.id/lora-gateway
@UUID = f33a20c9-0004-4d21-9df0-c45190670056


###

# @name set data task  by document id 
POST {{BASE_URL_GATEWAY_SERVICE}}/application/{{UUID}}/data HTTP/1.1
Content-Type: application/json

{
  "$.asset.license_plate": "B4334GI",
  "$.loan_structure.product_id": 1,
  "$.process.survey_task.survey_branch_id": "400",
  "$.process.survey_task.surveyor_employee_id": "000000",
  "$.process.operations_task.processing_branch_id": "400",
  "$.asset.bpkb_address": "Jl. villa permata",
  "$.asset.bpkb_number": "D123456789",
  "$.asset.bpkb_owner_name": "Budi",
  "$.asset.asset_code": "SUBARU.WRX.2MT",
  "$.asset.manufacturing_year": "2021",
  "$.asset.unit_color": "BLUE",
  "$.asset.chassis_number": "P1234567890129831",
  "$.asset.engine_number": "E1234567890",
  "$.asset.bpkb_invoice_number": "INV/2025/03/12/01ABC",
  "$.documents.bpkb_page_1.document_id": "c5db90e0-1837-4a6e-86da-571ba91d33d1",
  "$.documents.bpkb_page_2.document_id": "06cc9bcb-9ef4-4816-b5c4-7c3241f20757",
  "$.documents.bpkb_page_3.document_id": "1944edda-932e-4501-a332-a8819e3df23a",
  "$.documents.bpkb_page_4.document_id": "3914428a-f5e6-4193-8f63-575e9d726d39",
  "$.documents.bpkb_page_5.document_id": "6202e128-7095-4b9c-853f-47b750913e84",
  "$.documents.bpkb_invoice.document_id": "531da9ed-edf9-4065-877c-4181cd2b4b92",
  "$.documents.bpkb_receipt_2.document_id": "bc6ca9d9-2009-4b71-97d1-548b1a034cd6",
  "$.documents.stnk.document_id": "1bc60281-3655-41c3-a4df-75ce2bbd57a8",
  "$.documents.tax_notice.document_id": "1bc60281-3655-41c3-a4df-75ce2bbd57a8",
  "$.documents.ktp.document_id": "1bc60281-3655-41c3-a4df-75ce2bbd57a8",
  "$.documents.spouse_ktp.document_id": "1bc60281-3655-41c3-a4df-75ce2bbd57a8",
  "$.process.stnk_ocr_result.bpkb_number": "01234567",
  "$.process.stnk_ocr_result.chassis_number": "JM1DE11Y1D0112345",
  "$.process.stnk_ocr_result.engine_number": "ZYB12345",
  "$.process.stnk_ocr_result.license_plate": "B1234ZZ",
  "$.process.stnk_ocr_result.manufacturing_year": "2020",
  "$.process.stnk_ocr_result.stnk_expiration_date": "2025-03-12",
  "$.process.stnk_ocr_result.stnk_number": "07654321",
  "$.process.stnk_ocr_result.tax_expiration_date": "2025-03-12",
  "$.process.stnk_ocr_result.unit_color": "Hitam",
  "$.process.stnk_ocr_result.vehicle_brand": "TOYOTA",
  "$.process.bpkb_ocr_result.bpkb_address": "Jl Menara Avengers No 1",
  "$.process.bpkb_ocr_result.bpkb_invoice_number": "FA/AA/12345678",
  "$.process.bpkb_ocr_result.bpkb_number": "01234567",
  "$.process.bpkb_ocr_result.bpkb_owner_name": "Steve Rogers",
  "$.process.bpkb_ocr_result.chassis_number": "JM1DE11Y1D0112345",
  "$.process.bpkb_ocr_result.engine_number": "ZYB12345",
  "$.process.bpkb_ocr_result.license_plate": "B1234ZZ",
  "$.process.bpkb_ocr_result.manufacturing_year": "2020",
  "$.process.bpkb_ocr_result.unit_color": "Hitam",
  "$.process.bpkb_ocr_result.vehicle_brand": "TOYOTA",
  "$.asset.tax_expiration_date": "2025-03-12",
  "$.asset.stnk_number": "07654321",
  "$.asset.stnk_expiration_date": "2025-03-12",
  "$.asset.bpkb_ownership": "1",
  "$.documents.debtor_signature.document_id": "03f3dfcf-54ce-488d-9bcf-328a11e20be5",
  "$.documents.spouse_signature.document_id": "03f3dfcf-54ce-488d-9bcf-328a11e20be5",
  "$.documents.ppk.document_id": "03f3dfcf-54ce-488d-9bcf-328a11e20be5",
  "$.customer.personal.marital_status_code": "M",
  "$.spouse.ktp.name": "Diana",
  "$.customer.bank.account_name": "Data Test Yulia",
  "$.customer.bank.account_number": "111643252",
  "$.customer.bank.bank_code": "Bank Mandiri",
  "$.loan_structure.tenure": 24,
  "$.loan_structure.amount": 10000000,
  "$.loan_structure.billing_date": "2025-05-30",
  "$.loan_structure.capitalized_ntf_amount": 1000000,
  "$.loan_structure.ltv": 0.87,
  "$.loan_structure.monthly_installment": 300000,
  "$.loan_structure.funding_ratio": 0.87,
  "$.survey_financing.additional_fees.tax_arrears": 0,
  "$.survey_financing.additional_fees.tax_arrears_note": "",
  "$.survey_financing.additional_fees.vehicle_unblock_arrears": 0,
  "$.survey_financing.additional_fees.vehicle_unblock_arrears_note": ""
  }




###

# @name set data task  by document id 
POST {{BASE_URL_GATEWAY_SERVICE}}/application/{{UUID}}/data HTTP/1.1
Content-Type: application/json

{
  "$.customer.ktp.name": "DIAN SAOO",
	"$.channel.ekyc_authority": "bfi"
}

###

# @name ekyc
POST {{BASE_URL_GATEWAY_SERVICE}}/application/{{UUID}}/data HTTP/1.1
Content-Type: application/json

{
  "$.customer.ktp.nik": "5171010203040001",
  "$.customer.ktp.name": "SUDIDI",
  "$.customer.ktp.birth_date": "1994-04-01",
  "$.customer.ktp.birth_place": "jakarta",
  "$.customer.contact.mobile_number": "628123452342",
  "$.documents.ktp": "73fb642c-e69d-46b4-938f-9c0b8a90f153",
  "$.documents.selfie": "029492b1-a919-4b7c-85f9-b5b409ad6ec5",
  "$.channel.ekyc_authority": "bfi"
}

###

# @name create task list
POST {{BASE_URL_GATEWAY_SERVICE}}/application/start HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "id": "{{UUID}}",
  "name": "dp-ndf-v0_0_1"
}

###

# @name create people
POST {{BASE_URL_LTS}}/mgmt/people HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "user_id": "098180",
  "realm": "bfi_employees",
  "name": "DIAN SASTRE",
  "branch_id": "400",
  "partnership": {
    "dp_role": "ops_level_2",
    "dp_supervisor_id": "211111",
    "active": true
  }
}
